* -----------------------------------------------------
* XLS2GMS 2.8      24.5.3 r54322 Released Oct  1, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    C:\Users\robin\Google Drive\TU Delft\Thesis\GAMS\projdir\Optimal Power Flow (from MainPowerFlow)\Input_Data_MainOPF.xls
* Sheet:       Circuit_Data(Sheet2)
* Range:       $AD$4:$AG$35
* -----------------------------------------------------
        DCVref
n1.n1   0     
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
* -----------------------------------------------------
