* -----------------------------------------------------
* XLS2GMS 2.8      24.5.3 r54322 Released Oct  1, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    C:\Users\robin\Google Drive\TU Delft\Thesis\GAMS\projdir\Optimal Power Flow (from MainPowerFlow)\Input_Data_MainOPF.xls
* Sheet:       Circuit_Data(Sheet2)
* Range:       $B$4:$E$35
* -----------------------------------------------------
        Gline
n2.n3   1    
n3.n5   1    
n1.n4   1    
n4.n6   1    
             
             
             
             
             
             
             
             
             
             
             
n3.n2   1    
n5.n3   1    
n4.n1   1    
n6.n4   1    
             
             
             
             
             
             
             
             
             
             
             
             
* -----------------------------------------------------
